POST http://localhost:3000/api/appliedJob
Content-Type: application/json

{
  "companyName": "테스트",
  "position": "인턴",
  "appliedDate": "2025-11-11",
  "stages": [
    { "order": 1, "name": "서류", "status": "pass" },
    { "order": 2, "name": "코딩테스트", "status": "pending" },
    { "order": 3, "name": "1차 면접", "status": "pending" },
    { "order": 4, "name": "최종 면접", "status": "pending" }
  ],
  "contents": "기술 과제 제출 완료, 결과 대기 중입니다.",
  "progress": "in progress"
}

###

PATCH http://localhost:3000/api/appliedJob/2
Content-Type: application/json

{
  "companyName": "테스트",
  "position": "인턴",
  "appliedDate": "2025-11-03",
  "stages": [
    { "order": 1, "name": "서류", "status": "nonpass" },
    { "order": 2, "name": "인적성 검사", "status": "pending" },
    { "order": 3, "name": "코딩테스트", "status": "pending" },
    { "order": 4, "name": "1차 면접", "status": "pending" },
    { "order": 5, "name": "최종 면접", "status": "pending" }
  ],
  "contents": "",
  "progress": "completed"
}

###

GET http://localhost:3000/api/appliedJob
Content-Type: application/json

###

GET http://localhost:3000/api/appliedJob/1
Content-Type: application/json

###

DELETE http://localhost:3000/api/appliedJob/691204e468e155c3b7d5b87f
Content-Type: application/json